# Generated by Django 2.2.24 on 2021-12-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('imagem', models.FileField(default='empty', upload_to='')),
                ('tamanho', models.CharField(max_length=2)),
                ('descricao', models.CharField(max_length=300)),
                ('preco', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
            ],
        ),
    ]
